
language: java
jdk:
 - oraclejdk8

dist: trusty

stages:
- name: build
- name: snapshot
  if: branch = master AND env(RELEASE_BRANCH) = true
- name: pre-snapshot
  if: branch = pre-snapshot AND env(RELEASE_BRANCH) = true
- name: release
  if: branch = release AND env(RELEASE_BRANCH) = true

jobs:
    include:
    - stage: build
      script: ./gradlew clean build
    - stage: snapshot
      script: ./gradlew clean build artifactoryPublish -x test -Dsnapshot=true -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_API_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER
    - stage: pre-snapshot
      script: ./gradlew clean build artifactoryPublish -x test -Dsnapshot=true -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_API_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER
    - stage: release
      script: ./gradlew clean build bintrayUpload -x test -Dbintray.user=$BINTRAY_USER -Dbintray.key=$BINTRAY_API_KEY -Dbuild.number=$TRAVIS_BUILD_NUMBER -Dmaven.password=$MAVEN_PASSWORD -Dmaven.user=$MAVEN_USER

