
language: java
jdk:
- oraclejdk8

dist: trusty

stages:
- name: build
- name: release
  if: branch IN (release) AND type = push

jobs:
    include:
    - stage: build
      script: ./gradlew clean build
    - stage: release
      script: ./gradlew clean build publishToSonatype closeAndReleaseSonatypeStagingRepository -no-daemon --no-parallel -x test
